.TH ITUSB2-UDOFF 1
.SH NAME
itusb2-udoff \- disable USB data on ITUSB2 USB Test Switch
.SH SYNOPSIS
.B itusb2-udoff
.RI [ SERIALNUMBER ]
.SH DESCRIPTION
.B itusb2-udoff
disables USB data on the USB test switch, essentially by disconnecting both data
lines (D+ and D-). Conversely, you can invoke
.B itusb2-udon
to connect the data lines. You can also verify the corresponding status by
calling
.BR itusb2-status .

Specifying a serial number is optional.
.SH "EXIT STATUS"
Exits with a status of zero in case of success. Returns one should an error
occur.
.SH AUTHOR
Samuel Lourenço (samuel.fmlourenco@gmail.com).
.SH "SEE ALSO"
itusb2-attach(1), itusb2-detach(1), itusb2-enum(1), itusb2-info(1),
itusb2-list(1), itusb2-lockotp(1), itusb2-reset(1), itusb2-status(1),
itusb2-udon(1), itusb2-upoff(1), itusb2-upon(1)
